apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flashtools
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - analytics.yaml
  - ingress.yaml
images:
  - name: chochinize/flashtools-analytics
    newTag: c455b472ae9bf87554dad948eb20b6bc700339d7
  - name: chochinize/flashtools
    newTag: c455b472ae9bf87554dad948eb20b6bc700339d7
