apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flashtools
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - analytics.yaml
  - ingress.yaml
images:
  - name: chochinize/flashtools-analytics
    newTag: e5d0d03b6cb1298bff0895d6cdccfaecdbdf741a
  - name: chochinize/flashtools
    newTag: e5d0d03b6cb1298bff0895d6cdccfaecdbdf741a
