apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flashtools
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - analytics.yaml
  - ingress.yaml
images:
  - name: chochinize/flashtools-analytics
    newTag: f5676d9be1ba73cc4c6bc9cdb0bdfb46850cab17
  - name: chochinize/flashtools
    newTag: f5676d9be1ba73cc4c6bc9cdb0bdfb46850cab17
